'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace Q240884


	Partial Public Class _Default

		''' <summary>
		''' form1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' AccessDataSource1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected AccessDataSource1 As Global.System.Web.UI.WebControls.AccessDataSource

		''' <summary>
		''' ASPxPivotGrid1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxPivotGrid1 As Global.DevExpress.Web.ASPxPivotGrid.ASPxPivotGrid

		''' <summary>
		''' fieldCategoryID control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected fieldCategoryID As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

		''' <summary>
		''' fieldCategoryName control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected fieldCategoryName As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

		''' <summary>
		''' fieldProductID control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected fieldProductID As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

		''' <summary>
		''' fieldProductName control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected fieldProductName As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

		''' <summary>
		''' fieldUnitPrice control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected fieldUnitPrice As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

		''' <summary>
		''' fieldCompanyName control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected fieldCompanyName As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
	End Class
End Namespace
